# Generated by Django 5.2.5 on 2025-09-02 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skillmodel',
            old_name='percent',
            new_name='level',
        ),
        migrations.RemoveField(
            model_name='customusermodel',
            name='clients_served',
        ),
        migrations.RemoveField(
            model_name='customusermodel',
            name='projects_completed',
        ),
        migrations.RemoveField(
            model_name='customusermodel',
            name='website',
        ),
        migrations.RemoveField(
            model_name='customusermodel',
            name='years_experience',
        ),
        migrations.AddField(
            model_name='customusermodel',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='educationmodel',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
